# Generated by Django 3.2.5 on 2021-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('Student_Email', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=30)),
                ('Id_no', models.CharField(max_length=30)),
            ],
        ),
    ]
